services:
  prunemate:
    image: anoniemerd/prunemate:latest
    container_name: prunemate
    #ports:
    #  - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - prunemate_config_data:/config
    env_file:
      - .env
    restart: unless-stopped

volumes:
  prunemate_config_data:
    name: prunemate_config_data_volume
